 CREATE TABLE UNIDAD 
   (	UNI_BUS_UNI CHAR(5 BYTE) NOT NULL ENABLE, 
	UNI_NOMBRE VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	UNI_NOM_CORTO VARCHAR2(15 BYTE), 
	UNI_GERENTE CHAR(11 BYTE) NOT NULL ENABLE, 
	UNI_CONTRALOR CHAR(11 BYTE) NOT NULL ENABLE, 
	UNI_CIA CHAR(5 BYTE) NOT NULL ENABLE, 
	UNI_RFC VARCHAR2(20 BYTE) NOT NULL ENABLE
   ) ;
